---
- name: 0) 시간 동기화
  hosts: datacenters
#  vars:
#    timesync_ntp_servers:
#      - hostname: 2.pool.ntp.org
#        iburst: true
  roles:
    - rhel-system-roles.timesync

  post_tasks:
    - name : Set timezone
      community.general.timezone:
        name: "{{ host_timezone }}"
      notify: restart chronyd

  handlers:
    - name: restart chronyd
      ansible.builtin.service:
        name: chronyd
        state: restarted
